name: Simple CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: node
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
    - name: yarn install, build, and test
      env:
        NODE_OPTIONS: "--max_old_space_size=8192"
      run: |
        yarn install
        yarn test
    - name: deploy
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/master') }}
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
